Address error with hombrew install of rig.
New trust policy for homebrew casks (https://docs.brew.sh/Tap-Trust)
causes rig installation to fail with the following error:
Error: Refusing to load cask r-lib/rig/rig from untrusted tap r-lib/rig.
Run `brew trust --cask r-lib/rig/rig` or `brew trust r-lib/rig` to trust it.

This change in the installation process addresses
the error by directly installing the rig cask without
tapping the repository first, which avoids the trust issue.